FROM rocker/verse
MAINTAINER Abhishek Bhatia <abhatia@unc.edu>
RUN R -e "install.packages(\"reshape2\")"
RUN R -e "install.packages(\"shiny\")"
RUN R -e "install.packages(\"tinytex\")"
RUN R -e "tinytex::install_tinytex()"
RUN R -e "install.packages(\"tidyverse\")"
RUN R -e "install.packages(\"jsonlite\")"
RUN R -e "install.packages(\"data.table\")"
RUN R -e "install.packages(\"plyr\")"
RUN R -e "install.packages(\"stringr\")"
RUN R -e "install.packages(\"tidygeocoder\")"
RUN R -e "install.packages(\"usmap\")"
RUN R -e "install.packages(\"here\")"
RUN R -e "install.packages(\"fs\")"
RUN R -e "install.packages(\"janitor\")"
RUN R -e "install.packages(\"tidycensus\")"
RUN R -e "install.packages(\"labelled\")"
