.PHONY: clean
.PHONY: shiny
SHELL: /bin/bash

# Clean action to remove previously existing processed products
clean:
	rm -rf derived_data
	rm -rf figures
	rm -f report.pdf
	rm -f source_data/pcen_v2018_y18.txt.zip
	rm -f source_data/api_raw.json
	rm -rf source_data/AHRF_2018-2019
	rm -rf source_data/__MACOSX
	
# Final report for the Project
report.pdf: report.tex
	pdflatex report.tex

# Produce clean datasets used in this project
derived_data/yelp_tidy.csv: source_data/yelp_geocoded.csv\
			source_data/yelp_academic_dataset_business.json\
			scripts/util.R
			Rscript scripts/01_clean_yelp.R

derived_data/population_by_age.csv: source_data/*\
			scripts/util.R
			Rscript scripts/02_clean_pop.R

derived_data/percent_nonwhite_pop.csv: source_data/*\
			scripts/util.R
			Rscript scripts/02_clean_pop.R

derived_data/ahrf_subset.csv: source_data/*\
			scripts/util.R
			Rscript scripts/03_clean_ahrf.R

derived_data/api.csv: scripts/util.R
			Rscript scripts/04_clean_api.R

derived_data/plotting_data.csv: derived_data/yelp_tidy.csv\
			derived_data/population_by_age.csv\
			derived_data/percent_nonwhite_pop.csv\
			derived_data/ahrf_subset.csv\
			derived_data/api.csv\
			scripts/util.R
			Rscript scripts/05_clean_merged.R

# Produce figures generated by this report
# Note: this will create all univariate plots to stitch together into a final figure

figures/fig_univariate_all.pdf: derived_data/plotting_data.csv scripts/util.R
		Rscript scripts/06_fig_univariate.R 
figures/fig_univariate_all.png: derived_data/plotting_data.csv scripts/util.R
		Rscript scripts/06_fig_univariate.R 

# Note: this will create all bivariate plots to stitch together into a final figure
figures/fig_bivariate_retail.pdf: derived_data/plotting_data.csv scripts/util.R
		Rscript scripts/07_fig_univariate.R 
figures/fig_bivariate_retail.png: derived_data/plotting_data.csv scripts/util.R
		Rscript scripts/07_fig_univariate.R 

figures/fig_bivariate_api.pdf: derived_data/plotting_data.csv scripts/util.R
		Rscript scripts/08_fig_univariate.R 
figures/fig_bivariate_api.png: derived_data/plotting_data.csv scripts/util.R
		Rscript scripts/08_fig_univariate.R 

# Shiny setup
shiny: scripts/shiny.R
	Rscript scripts/99_shiny.R ${PORT}