.PHONY: clean
.PHONY: shiny
SHELL: /bin/bash

# Clean action to remove previously existing processed products
clean:
	rm -rf derived_data
	rm -rf figures
	rm -f report.pdf
	rm -f source_data/pcen_v2018_y18.txt.zip
	rm -f source_data/api_raw.json
	rm -rf source_data/AHRF_2018-2019
	rm -rf source_data/__MACOSX
	
# Final report for the Project
report.pdf: report.tex
	pdflatex report.tex

# Produce clean datasets used in this project
derived_data/analytic_data.csv: source_data/*\
			scripts/util.R
			Rscript scripts/cleanup.R

derived_data/plotting_data.csv: source_data/*\
			scripts/util.R
			Rscript scripts/cleanup.R
# Produce figures generated by this report
figures: source_data/*\
		derived_data/plotting_data.csv
		scripts/util.R
		Rscript scripts/cleanup.R \
		Rscript scripts/figures.R

# Shiny setup
shiny: scripts/shiny.R
	Rscript scripts/shiny.R ${PORT}